import { hsiFromCurrent, riskFromCurrent, riskLabel, METRIC_LABELS, checkDeviations } from './metrics';

export function generateReport(patient, current, baseline, history, alerts, generatedBy) {
  const hsi = hsiFromCurrent(current, baseline);
  const risk = riskFromCurrent(current, baseline);
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' });
  const trend = history.length > 1 ? hsiFromCurrent(history[history.length - 1], history[0]) : hsi;

  let report = '';
  report += '═══════════════════════════════════════════════════════════\n';
  report += '              KUTAKSHA HEALTH MONITORING REPORT\n';
  report += '═══════════════════════════════════════════════════════════\n\n';
  report += `Generated: ${dateStr}\n`;
  report += `Generated By: ${generatedBy}\n`;
  report += `Report Type: AI Digital Twin Assessment\n\n`;

  report += '── PATIENT INFORMATION ──────────────────────────────────\n';
  report += `Name: ${patient.name}\n`;
  report += `Age: ${patient.age}\n`;
  report += `Condition: ${patient.condition}\n`;
  report += `Patient ID: ${patient.id}\n\n`;

  report += '── HEALTH SUMMARY ───────────────────────────────────────\n';
  report += `Health Stability Index (HSI): ${hsi}/100\n`;
  report += `Risk Score: ${risk}%\n`;
  report += `Risk Level: ${riskLabel(risk)}\n`;
  report += `Trend Direction: ${trend >= 70 ? 'Stable' : trend >= 50 ? 'Watch' : 'Declining'}\n\n`;

  report += '── METRICS vs BASELINE ──────────────────────────────────\n';
  report += `${'Metric'.padEnd(25)} ${'Baseline'.padStart(10)} ${'Current'.padStart(10)} ${'Change'.padStart(10)} ${'Status'.padStart(10)}\n`;
  report += '─'.repeat(70) + '\n';

  for (const [key, meta] of Object.entries(METRIC_LABELS)) {
    const curr = current[key];
    const base = baseline[key];
    const change = base !== 0 ? Math.round(((curr - base) / base) * 100) : 0;
    const dev = Math.abs(change);
    const status = dev >= 40 ? 'CRITICAL' : dev >= 20 ? 'WARNING' : 'NORMAL';
    const unit = meta.unit ? ' ' + meta.unit : '';
    report += `${meta.label.padEnd(25)} ${(base.toFixed(meta.decimals) + unit).padStart(10)} ${(curr.toFixed(meta.decimals) + unit).padStart(10)} ${((change > 0 ? '+' : '') + change + '%').padStart(10)} ${status.padStart(10)}\n`;
  }

  report += '\n── ACTIVE ALERTS (≥20% Deviation) ───────────────────────\n';
  if (alerts.length === 0) {
    report += 'No active alerts. All metrics within acceptable range.\n';
  } else {
    alerts.forEach((a, i) => {
      report += `${i + 1}. [${a.severity.toUpperCase()}] ${a.message}\n`;
    });
  }

  report += '\n── RECENT TRACKING HISTORY ──────────────────────────────\n';
  const recent = history.slice(-10);
  if (recent.length === 0) {
    report += 'No tracking history available.\n';
  } else {
    report += `${'Time'.padEnd(12)} ${'Speed'.padStart(8)} ${'Activity'.padStart(10)} ${'Balance'.padStart(10)} ${'HSI'.padStart(6)} ${'Risk'.padStart(6)}\n`;
    report += '─'.repeat(60) + '\n';
    recent.forEach((h) => {
      const t = new Date(h.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });
      const hHsi = hsiFromCurrent(h, baseline);
      const hRisk = riskFromCurrent(h, baseline);
      report += `${t.padEnd(12)} ${h.walking_speed.toFixed(2).padStart(8)} ${(h.activity_level + '%').padStart(10)} ${(h.balance_score + '%').padStart(10)} ${String(hHsi).padStart(6)} ${(hRisk + '%').padStart(6)}\n`;
    });
  }

  report += '\n── RECOMMENDATIONS ──────────────────────────────────────\n';
  if (risk >= 70) {
    report += '• Immediate caregiver intervention recommended\n';
    report += '• Schedule physician consultation within 24 hours\n';
    report += '• Monitor mobility metrics every 2 hours\n';
  } else if (risk >= 40) {
    report += '• Increase monitoring frequency to every 4 hours\n';
    report += '• Encourage light physical activity\n';
    report += '• Review medication and nutrition plan\n';
  } else {
    report += '• Continue regular preventive monitoring\n';
    report += '• Maintain current activity levels\n';
    report += '• Next scheduled review in 7 days\n';
  }

  report += '\n═══════════════════════════════════════════════════════════\n';
  report += '  Kutaksha — Privacy-Preserving Preventive Healthcare\n';
  report += '  This report is generated by AI and should be reviewed by\n';
  report += '  a qualified healthcare professional.\n';
  report += '═══════════════════════════════════════════════════════════\n';

  return report;
}

export function downloadReport(patient, current, baseline, history, generatedBy) {
  const alerts = checkDeviations(current, baseline, 20);
  const report = generateReport(patient, current, baseline, history, alerts, generatedBy);
  const blob = new Blob([report], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `Kutaksha_Report_${patient.name.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadCSV(patient, history, baseline) {
  const headers = ['timestamp', 'walking_speed', 'activity_level', 'sitting_minutes', 'balance_score', 'tremor_index', 'gait_rhythm', 'posture_stability', 'step_stride', 'fatigue_index', 'movement_variability', 'hsi', 'risk'];
  const rows = history.map((h) => {
    const hsi = hsiFromCurrent(h, baseline);
    const risk = riskFromCurrent(h, baseline);
    return [new Date(h.timestamp).toISOString(), h.walking_speed, h.activity_level, h.sitting_minutes, h.balance_score, h.tremor_index, h.gait_rhythm, h.posture_stability ?? baseline.posture_stability, h.step_stride ?? baseline.step_stride, h.fatigue_index ?? baseline.fatigue_index, h.movement_variability ?? baseline.movement_variability, hsi, risk].join(',');
  });
  const csv = [headers.join(','), ...rows].join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `Kutaksha_Metrics_${patient.name.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
